<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../XauScalp.Domain/XauScalp.Domain.csproj" />
    <ProjectReference Include="../XauScalp.MarketData/XauScalp.MarketData.csproj" />
    <ProjectReference Include="../XauScalp.DecisionModels/XauScalp.DecisionModels.csproj" />
  </ItemGroup>
</Project>
